2021-05-24 09:36:14,656 INFO    MainThread:19522 [wandb_setup.py:_flush():69] setting env: {}
2021-05-24 09:36:14,657 INFO    MainThread:19522 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-24 09:36:14,657 INFO    MainThread:19522 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/code/notebooks/wandb/run-20210524_093614-10dkoexf/logs/debug.log
2021-05-24 09:36:14,657 INFO    MainThread:19522 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/code/notebooks/wandb/run-20210524_093614-10dkoexf/logs/debug-internal.log
2021-05-24 09:36:14,658 INFO    MainThread:19522 [wandb_init.py:init():369] calling init triggers
2021-05-24 09:36:14,658 INFO    MainThread:19522 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-24 09:36:14,658 INFO    MainThread:19522 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 2arpnahm
2021-05-24 09:36:14,659 INFO    MainThread:19522 [wandb_run.py:finish():1208] finishing run rolypolyvg295/ocr/2arpnahm
2021-05-24 09:36:14,661 INFO    MainThread:19522 [jupyter.py:save_history():320] not saving jupyter history
2021-05-24 09:36:14,661 INFO    MainThread:19522 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-24 09:36:14,661 INFO    MainThread:19522 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-24 09:36:14,661 INFO    MainThread:19522 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-24 09:36:14,662 INFO    MainThread:19522 [wandb_run.py:_restore():1507] restore
2021-05-24 09:36:14,666 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-05-24 09:36:15,013 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-05-24 09:36:15,842 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 3079
}

2021-05-24 09:36:16,203 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3462
  total_bytes: 3462
}

2021-05-24 09:36:16,305 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3462
  total_bytes: 3462
}

2021-05-24 09:36:16,407 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3462
  total_bytes: 3462
}

2021-05-24 09:36:16,509 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3462
  total_bytes: 3462
}

2021-05-24 09:36:16,610 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3462
  total_bytes: 3462
}

2021-05-24 09:36:16,712 INFO    MainThread:19522 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3462
  total_bytes: 3462
}

2021-05-24 09:36:17,826 INFO    MainThread:19522 [wandb_run.py:_show_files():1879] logging synced files
2021-05-24 09:36:17,831 INFO    MainThread:19522 [wandb_init.py:init():418] starting backend
2021-05-24 09:36:17,831 INFO    MainThread:19522 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-24 09:36:17,834 INFO    MainThread:19522 [backend.py:ensure_launched():132] starting backend process...
2021-05-24 09:36:17,874 INFO    MainThread:19522 [backend.py:ensure_launched():137] started backend process with pid: 6215
2021-05-24 09:36:17,876 INFO    MainThread:19522 [wandb_init.py:init():423] backend started and connected
2021-05-24 09:36:17,894 INFO    MainThread:19522 [wandb_init.py:init():465] updated telemetry
2021-05-24 09:36:17,895 INFO    MainThread:19522 [wandb_init.py:init():484] communicating current version
2021-05-24 09:36:18,765 INFO    MainThread:19522 [wandb_init.py:init():489] got version response 
2021-05-24 09:36:18,766 INFO    MainThread:19522 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-24 09:36:18,985 INFO    MainThread:19522 [wandb_init.py:init():522] starting run threads in backend
2021-05-24 09:36:21,719 INFO    MainThread:19522 [wandb_run.py:_console_start():1565] atexit reg
2021-05-24 09:36:21,720 INFO    MainThread:19522 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-24 09:36:21,720 INFO    MainThread:19522 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-24 09:36:21,720 INFO    MainThread:19522 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-24 09:36:21,720 INFO    MainThread:19522 [wandb_init.py:init():546] run started, returning control to user process
2021-05-24 09:59:38,597 INFO    MainThread:19522 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-24 09:59:38,598 INFO    MainThread:19522 [wandb_run.py:_restore():1507] restore
2021-05-24 09:59:38,600 INFO    MainThread:19522 [wandb_run.py:_restore():1507] restore
